{"name": "Проверка негативного сценариея принятия заказа с неправильный ID", "status": "passed", "description": "Фикстура создает курьера и заказ, после проеряется негативный сценарий принятия заказа {negative_data}", "attachments": [{"name": "stdout", "source": "227d1f9d-955a-4048-948e-e120aee78773-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "negative_data", "value": "{'courier_id': 99999999, 'order_id': True, 'code': 404, 'message': 'Курьера с таким id не существует'}"}], "start": 1757920941693, "stop": 1757920942093, "uuid": "d9f752cd-8c9b-4814-ae67-8627843ac263", "historyId": "40a5fffe4e76092dc4d650c725495d97", "testCaseId": "3eb2b6a91772a0b54f59ffa7d7a7b071", "fullName": "tests.test_accept_order.TestAcceptOrder#test_wrong_ids_negative_check_response", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "RUMS01CW-F915A8"}, {"name": "thread", "value": "12672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}], "titlePath": ["tests", "test_accept_order.py", "TestAcceptOrder"]}